apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - opm-flow/job.yaml
  - opm-flow/configmap.yaml

commonLabels:
  app.kubernetes.io/part-of: clarissa
  app.kubernetes.io/managed-by: kustomize
